# Generated by Django 4.2 on 2023-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bootstrap_wysihtml5", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="wysihtml5_data",
            new_name="bootstrap_wysihtml5_data",
        ),
    ]
